# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'AtChat' do
pod 'XMPPFramework', :git => "https://github.com/robbiehanson/XMPPFramework.git", :branch => 'master'
pod 'SDWebImage', '~> 3.8.1'
pod 'YYKit'
pod 'MJRefresh', '~> 3.1.12'
pod 'MBProgressHUD'
end

